name: Build listing images (VRBO + ETSY)

on:
  workflow_dispatch:
  push:
    branches: [ Vrbo ]
    paths:
      - scripts/build-images.js
      - .github/workflows/build.yml

permissions:
  contents: write

jobs:
  build-both:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: VRBO
            SHEET_TAB: "VRBO"
            OUT_DIR: "images/vrbo"
            WIDTH: "575"
            HEIGHT: "325"
          - name: ETSY
            SHEET_TAB: "ETSY"
            OUT_DIR: "images/etsy"
            WIDTH: "325"
            HEIGHT: "575"

    steps:
      - name: Checkout Vrbo branch
        uses: actions/checkout@v4
        with:
          ref: Vrbo
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i sharp@^0.33 node-fetch@3 csv-parse@^5

      - name: Build images for ${{ matrix.name }}
        env:
          SHEET_TAB: ${{ matrix.SHEET_TAB }}
          OUT_DIR: ${{ matrix.OUT_DIR }}
          WIDTH: ${{ matrix.WIDTH }}
          HEIGHT: ${{ matrix.HEIGHT }}
        run: node scripts/build-images.js

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Stage outputs
        run: git add images/

      - name: Commit if changes
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update processed images for ${{ matrix.name }}"
          fi

      - name: Rebase on remote Vrbo
        run: |
          git fetch origin Vrbo
          set -e
          if ! git rebase origin/Vrbo; then
            git rebase --abort || true
            git pull --no-rebase origin Vrbo
          fi

      - name: Push changes
        run: git push origin HEAD:Vrbo
